name: ads2
channels:
  - conda-forge
  - defaults
dependencies:
  - fonttools=4.25.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - numba=0.58.1
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - pandas=2.1.4
  - pillow=10.0.1
  - python=3.10.13
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - umap-learn=0.5.3


